// java-example/webauthn/webauthn/src/components/SignIn.vue
<template>
  <v-container>
    <v-layout justify-center>
      <v-flex xs12 md12>
        <v-form ref="form">
          <v-card outlined tile>
            <v-text-field
              id="email"
              v-model="email"
              label="e-mail"
              clearable
              :rules="[
                (email) => !!email || 'E-mail is required',
                email && email.length > 0
              ]"
              required
            />
          </v-card>
          <v-card outlined tile>
            <v-btn color="primary" name="signIn" @click="authentication">
              サインイン
            </v-btn>
          </v-card>
        </v-form>
      </v-flex>
      <v-flex xs12 md12>
        アカウントは作成済みですか？
        <v-btn block color="primary" name="signIn" sm="12" @click="showSignUp">
          サインアップ
        </v-btn>
      </v-flex>
      <v-flex xs24 md24>
        <v-card outlined tile>
          <v-alert v-show="!!status" v-bind:type="this.status">
            {{ message }}
          </v-alert>
        </v-card>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script lang="ts">
import { Vue, Component, Emit } from 'vue-property-decorator'
import WebAuthnClient from '../plugins/types'
import { WebAuthnPage } from '../store'

@Component
export default class SignIn extends Vue {
  displayName: string = ''
  email: string = ''
  status: string = ''
  message: string = ''
  auth: Boolean = false

  @Emit()
  showSignUp() {
    this.$accessor.changePage(WebAuthnPage.SignUp)
  }

  @Emit()
  showIndex() {
    this.$accessor.changePage(WebAuthnPage.Index)
  }

  @Emit()
  async authentication() {
    try {
      if (!window.PublicKeyCredential) {
        this.status = 'error'
        this.message = '未対応のブラウザです'
        return
      }

      if (!(this.$refs.form as Vue & { validate: () => boolean }).validate()) {
        return
      }

      const email: string = this.email
      const response: WebAuthnClient.CredentialRequestOptions = await this.$assertionOptions<
        WebAuthnClient.CredentialRequestOptions
      >(email)

      this.status = ''

      const options = this.convertRequestOptions(response)

      const credential = await navigator.credentials
        .get(options)
        .then((reply: Credential | null) => {
          if (reply != null) {
            return reply as PublicKeyCredential
          } else {
            throw new Error('unmatched type')
          }
        })
        .catch((reason) => {
          throw reason
        })

      const json = await this.credentialToJSON(credential)

      const ret = await this.$authenticationFinish(json)

      this.showIndex()

      return ret
    } catch (error) {
      this.status = 'error'
      this.message = error
    }
  }

  private convertRequestOptions(
    source: WebAuthnClient.CredentialRequestOptions
  ): CredentialRequestOptions {
    const allowCredentials =
      source.allowCredentials != null ? source.allowCredentials : []

    const credentialRequestOptions: PublicKeyCredentialRequestOptions = {
      allowCredentials: allowCredentials.map((credential) => {
        return {
          id: this.base64ToArrayBuffer(credential.id),
          type: credential.type,
          transports: credential.transports
        } as PublicKeyCredentialDescriptor
      }),
      challenge: this.stringToArrayBuffer(source.challenge.value),
      extensions: source.extensions,
      rpId: source.rpId,
      timeout: source.timeout,
      userVerification: source.userVerification
    }
    return {
      publicKey: credentialRequestOptions
    }
  }

  private async credentialToJSON(
    credential: PublicKeyCredential
  ): Promise<WebAuthnClient.AuthenticatorAssertionJSON> {
    const response = await (credential.response as AuthenticatorAssertionResponse)
    const credentialJSON: WebAuthnClient.AuthenticatorAssertionJSON = {
      credentialId: this.arrayBufferToBase64(credential.rawId),
      clientDataJSON: this.arrayBufferToBase64(response.clientDataJSON),
      authenticatorData: this.arrayBufferToBase64(response.authenticatorData),
      signature: this.arrayBufferToBase64(response.signature),
      clientExtensionsJSON: JSON.stringify(
        credential.getClientExtensionResults()
      )
    }
    return credentialJSON
  }

  private stringToArrayBuffer(string: string): Uint8Array {
    return new TextEncoder().encode(string)
  }

  private base64ToArrayBuffer(base64String: string): Uint8Array {
    return Uint8Array.from(atob(base64String), (_) => {
      return _.charCodeAt(0)
    })
  }

  private arrayBufferToBase64(arrayBuffer: ArrayBuffer): string {
    return btoa(String.fromCharCode(...new Uint8Array(arrayBuffer)))
  }
}
</script>

<style>
.container {
  margin: 0 auto;
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  text-align: center;
}

.title {
  font-family: 'Quicksand', 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
    'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  display: block;
  font-weight: 300;
  font-size: 100px;
  color: #35495e;
  letter-spacing: 1px;
}

.subtitle {
  font-weight: 300;
  font-size: 42px;
  color: #526488;
  word-spacing: 5px;
  padding-bottom: 15px;
}

.links {
  padding-top: 15px;
}
</style>

// java-example/spring-boot/webauthn/webauthn-client/src/components/SignIn/index.tsx
import {
  Button, Link, TextField, Box,
} from '@mui/material';
import React from 'react';
import { SubmitHandler, useForm } from 'react-hook-form';

export interface Challenge {
  value: string
}

export interface ICredentialOptionsCredentialDescriptor {
  id: string
  transports?: AuthenticatorTransport[]
  type: PublicKeyCredentialType
}

export interface IAuthenticatorAssertionJSON {
  credentialId: string
  clientDataJSON: string
  authenticatorData: string
  signature: string
  clientExtensionsJSON: string
}

export interface ICredentialRequestOptions {
  challenge: Challenge
  timeout?: number
  allowCredentials?: ICredentialOptionsCredentialDescriptor[]
  extensions?: AuthenticationExtensionsClientInputs
  rpId?: string
  userVerification?: UserVerificationRequirement
}

interface SignInProp {
  container?: Element,
  onAuthenticated: () => void,
  onError: (message: string) => void,
  onShowSignUp: () => void
}

async function assertionOptions<T>(email: string): Promise<T> {
  const mail = email;
  return (await fetch(
    '/api/assertion/options', {
      method: 'POST',
      body: JSON.stringify({
        email: mail,
      }),
      headers: { 'Content-Type': 'application/json' },
    },
  )).json();
}

async function authenticationFinish<T>(
  credential: IAuthenticatorAssertionJSON,
): Promise<T> {
  const response = await fetch(
    '/api/assertion/result', {
      method: 'POST',
      body: JSON.stringify({
        clientDataJSON: credential.clientDataJSON,
        credentialId: credential.credentialId,
        authenticatorData: credential.authenticatorData,
        signature: credential.signature,
      }),
      headers: { 'Content-Type': 'application/json' },
    },
  );
  return response.bodyUsed && response.body !== null ? response.json() : undefined;
}

const SignIn = (props: SignInProp): JSX.Element => {
  type Inputs = {
    email: string,
  };

  const { register, handleSubmit } = useForm<Inputs>();

  const stringToArrayBuffer = (string: string): Uint8Array => new TextEncoder().encode(string);

  const base64ToArrayBuffer = (base64String: string): Uint8Array => Uint8Array.from(atob(base64String), (_) => _.charCodeAt(0));

  const arrayBufferToBase64 = (arrayBuffer: ArrayBuffer): string => btoa(String.fromCharCode(...new Uint8Array(arrayBuffer)));

  const credentialToJSON = async (
    credential: PublicKeyCredential,
  ): Promise<IAuthenticatorAssertionJSON> => {
    const response = (credential.response as AuthenticatorAssertionResponse);
    const credentialJSON: IAuthenticatorAssertionJSON = {
      credentialId: arrayBufferToBase64(credential.rawId),
      clientDataJSON: arrayBufferToBase64(response.clientDataJSON),
      authenticatorData: arrayBufferToBase64(response.authenticatorData),
      signature: arrayBufferToBase64(response.signature),
      clientExtensionsJSON: JSON.stringify(
        credential.getClientExtensionResults(),
      ),
    };
    return credentialJSON;
  };

  const convertRequestOptions = (source: ICredentialRequestOptions): CredentialRequestOptions => {
    const allowCredentials = source.allowCredentials != null ? source.allowCredentials : [];

    const credentialRequestOptions: PublicKeyCredentialRequestOptions = {
      allowCredentials: allowCredentials.map((credential) => ({
        id: base64ToArrayBuffer(credential.id),
        type: credential.type,
        transports: credential.transports,
      } as PublicKeyCredentialDescriptor)),
      challenge: stringToArrayBuffer(source.challenge.value),
      extensions: source.extensions,
      rpId: source.rpId,
      timeout: source.timeout,
      userVerification: source.userVerification,
    };
    return {
      publicKey: credentialRequestOptions,
    };
  };

  async function authentication(email: string): Promise<void> {
    props.onError('');

    if (window === undefined) {
      return;
    }
    if (!window.PublicKeyCredential) {
      props.onError('未対応のブラウザです');
      return;
    }

    try {
      const response = await assertionOptions<ICredentialRequestOptions>(email);

      const options = convertRequestOptions(response);

      const credential = await navigator.credentials
        .get(options)
        .then((reply: Credential | null) => {
          if (reply !== null) {
            return reply as PublicKeyCredential;
          }
          throw new Error('unmatched type');
        })
        .catch((reason) => {
          throw reason;
        });

      const json = await credentialToJSON(credential);

      await authenticationFinish<void>(json);
      props.onAuthenticated();
    } catch (error) {
      props.onError((error as Error).message);
    }
  }

  const onSubmit: SubmitHandler<Inputs> = (data: Inputs) => {
    authentication(data.email)
      .catch((error) => {
        props.onError(JSON.stringify(error, null, 2));
      });
  };

  return (
    <div>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Box>
          <TextField
            required={true}
            label="e-mail"
            {...register('email', { required: true })}
          />
        </Box>
        <Button type="submit" variant="contained" color="primary">サインイン</Button>
      </form>
      <div>
        <Box>
          アカウントは作成済みですか？
        </Box>
        <Link onClick={props.onShowSignUp}>サインアップ</Link>
      </div>
    </div>
  );
};

export default SignIn;
